package config

var Environment = map[string]any{
	"environment":        "local",
	"name":               "Master Service",
	"description":        "Master Service",
	"port":               8000,
	"endpoint":           "/api/v1/master",
	"version":            "v1.0.0",
	"prefork":            false,
	"timezone":           "UTC",
	"db_host":            "localhost",
	"db_port":            55432,
	"db_name":            "postgres",
	"db_user":            "postgres",
	"db_password":        "postgres",
	"db_table_prefix":    "",
	"redis_host":         "localhost",
	"redis_port":         6378,
	"redis_password":     "",
	"redis_index":        0,
	"redis_queue_name":   "sensor_data_queue",
	"redis_dlq_name":     "sensor_data_dlq",
	"mongo_host":         "localhost",
	"mongo_port":         27017,
	"mongo_username":     "admin",
	"mongo_password":     "password",
	"mongo_database":     "myapp",
	"cache_ttl_seconds":  3600,
	"enable_migration":   true,
	"client_service_url": "http://localhost:8002",
	"max_retries":        3,
	"retry_backoff_base": 1,
	"api_secret_key":     "Fr46VTqmt3j7AjT0hDa",
	"client_host":        "localhost",
	"client_port":        8002,
}
