package config

var Environment = map[string]any{
	"ENVIRONMENT":        "local",
	"NAME":               "Master Service",
	"DESCRIPTION":        "Master Service",
	"PORT":               8000,
	"ENDPOINT":           "/api/v1/master",
	"VERSION":            "v1.0.0",
	"PREFORK":            false,
	"TIMEZONE":           "UTC",
	"DB_HOST":            "localhost",
	"DB_PORT":            55432,
	"DB_NAME":            "postgres",
	"DB_USER":            "postgres",
	"DB_PASSWORD":        "postgres",
	"DB_TABLE_PREFIX":    "",
	"REDIS_HOST":         "localhost",
	"REDIS_PORT":         6378,
	"REDIS_PASSWORD":     "",
	"REDIS_INDEX":        0,
	"REDIS_QUEUE_NAME":   "sensor_data_queue",
	"REDIS_DLQ_NAME":     "sensor_data_dlq",
	"MONGO_HOST":         "localhost",
	"MONGO_PORT":         27017,
	"MONGO_USERNAME":     "admin",
	"MONGO_PASSWORD":     "password",
	"MONGO_DATABASE":     "myapp",
	"CACHE_TTL_SECONDS":  3600,
	"ENABLE_MIGRATION":   true,
	"CLIENT_SERVICE_URL": "http://localhost:8002",
	"MAX_RETRIES":        3,
	"RETRY_BACKOFF_BASE": 1,
	"API_SECRET_KEY":     "secret-key",
}
